# Site settings
title: Candy's
email: 123wxtong@sina.com
description: > # this means to ignore newlines until "baseurl:"
 多写代码，才能提高更多~多挖坑，多填坑，努力成为填坑高手！.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://candywxt.github.io/" # the base hostname & protocol for your site
twitter_username: 00wxt
github_username: candywxt

# Build settings
markdown: kramdown
#覆盖摘要
excerpt_separator: ""